var projectConstants = {
  SINGLE_PROJECT_RECEIVED: "SINGLE_PROJECT_RECEIVED",
	ALL_PROJECTS_RECEIVED: "ALL_PROJECTS_RECEIVED",
  NEW_PAGE_PROJECTS_RECEIVED: "NEW_PAGE_PROJECTS_RECEIVED"
};

module.exports = projectConstants;
